title: Friends of Kyrgyzstan
subtitle: A place to connect with others who love Kyrgyzstan.

url: "https://www.friendsofkyrgyzstan.org"
google-analytics: UA-12358141-35

sass:
    load_paths:
        - _sass
        - node_modules

exclude: []

include: ["_pages"]

permalink: /:title/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache


collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
    values:
      author: fokgz
      image: /assets/images/kyrgyzstan-mountain-landscape.jpg
      description: A place to connect with others who love Kyrgyzstan.
  - scope:
      type: page
    values:
      layout: "page"
  - scope:
      path: ""
      type: posts
    values:
      layout: "post"
  - scope:
      path: ""
      type: authors
    values:
      layout: "author"

twitter:
  # username: benbalter
  card: summary
# facebook:
#  app_id: 1234
#  publisher: 1234
#  admins: 1234
social:
  name: Friends of Kyrgyzstan
  links:
    - https://www.facebook.com/FriendsOfKyrgyzstan/
webmaster_verifications:
  google: 1234
  bing: 1234
  alexa: 1234
  yandex: 1234
  baidu: 1234

disqus: fokgz
mailchimp-list: https://friendsofkyrgyzstan.us10.list-manage.com/subscribe/post?u=db91617a7211166ac946aeb91&amp;id=08e9a611b3

compress_html:  
  clippings: all  
  comments: ["<!-- ", " -->"] 
  endings: [html, head, body, li, dt, dd, rt, rp, optgroup, option, colgroup, caption, thead, tbody, tfoot, tr, td, th] 
  profile: false 
  blanklines: false 
  ignore: 
    envs: []
