title: Friends of Kyrgyzstan
subtitle: A place to connect with others who love Kyrgyzstan.

url: "https://www.friendsofkyrgyzstan.org"
google-analytics: UA-12358141-35

permalink: /:title/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache

collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
    values:
      author: fokgz
      image: /assets/images/kyrgyzstan-mountain-landscape.jpg
      description: A place to connect with others who love Kyrgyzstan.
  - scope:
      type: pages
    values:
      layout: "page"
  - scope:
      path: ""
      type: posts
    values:
      layout: "post"
  - scope:
      path: ""
      type: authors
    values:
      layout: "author"

twitter:
  # username: benbalter
  card: summary_large_image

facebook:
  app_id: 636734270387509
  admins: 748068695307188

social:
  name: Friends of Kyrgyzstan
  links:
    - https://www.facebook.com/FriendsOfKyrgyzstan/
    - https://www.instagram.com/fokgz/

disqus: fokgz
mailchimp-list: https://friendsofkyrgyzstan.us10.list-manage.com/subscribe/post?u=db91617a7211166ac946aeb91&amp;id=08e9a611b3

compress_html:  
  clippings: all  
  comments: ["<!-- ", " -->"] 
  endings: [html, head, body, li, dt, dd, rt, rp, optgroup, option, colgroup, caption, thead, tbody, tfoot, tr, td, th] 
  profile: false 
  blanklines: false 
  ignore: 
    envs: []
